---
title: "Game of Thromes Character Ratings"
author: "Angela Zoss"
date: "2/19/2019"
output: html_document
---

## Setup your environment

```{r}

# Load required libraries

library(tidyverse)

```

## Load your data

```{r}

# data comes from https://int.nyt.com/newsgraphics/2017/2017-07-17-got-matrix/mean.json
# data based on ratings using tool at https://www.nytimes.com/interactive/2017/08/09/upshot/game-of-thrones-chart.html

got <- read_csv("data/got_ratings.csv")

```

## Create a basic plot

```{r}

# Remember the basic steps:
# - set the data (main function)
# - choose a shape layer
# - map variables to aesthetics using aes() -> start with x and y in main function



```

## Set the alpha (transparency) of all points to .75

```{r}

# check ?geom_point to see names of the different options available
# where should the new option go? what layer? inside or outside of aesthetics?



```

## Add labels

```{r}

# hint: check https://ggplot2.tidyverse.org/reference/#section-layer-geoms for all geom options



```

## Fix label overlap

```{r}

# hint: look at ?geom_text for an option that might change the position slightly
# where should the new option go? what layer? inside or outside of aesthetics?



```

## Add colors

```{r}

# add gender as a color three different ways:
# - points only
# - labels only
# - both



```

## Turn off legend for text layer

```{r}

# hint: there is another property for the geom_text layer that might help



```

## Split the chart up into separate charts for each family (loyalty group)

```{r}

# Hint: check https://ggplot2.tidyverse.org/reference/ for facet layers



```
