---
title: "Game of Thromes Character Ratings"
author: "Angela Zoss"
date: "8/12/2018"
output: github_document
---

## Setup your environment

```{r}

# Load required libraries

library(tidyverse)

```

## Load your data

```{r}

# data comes from https://int.nyt.com/newsgraphics/2017/2017-07-17-got-matrix/mean.json
# data based on ratings using tool at https://www.nytimes.com/interactive/2017/08/09/upshot/game-of-thrones-chart.html

got <- read_csv("data/got_ratings.csv")

```

## Plot the data

```{r}

# add a geom and an aes() function with the correct x and y variables

ggplot(got) +
  geom_point(aes(x=moral,y=physical))


```

## Add labels

```{r}

#ggplot(got) +
#  geom_point(aes(x=moral,y=physical)) + 
#  geom_text(aes(label=label))

```


```{r}

# hint: check https://ggplot2.tidyverse.org/reference/#section-layer-geoms for all geom options

ggplot(got, aes(x=moral,y=physical)) + 
  geom_point() + 
  geom_text(aes(label=label))

```

## Fix label overlap

```{r}

# hint: look at ?geom_text for a property that might change the position slightly
# once you've found something to try, be careful: are you adding a new variable, or is it a constant change?

ggplot(got, aes(x=moral,y=physical)) + 
  geom_point() + 
  geom_text(aes(label=label), nudge_y = -.025)

```

## Add colors

```{r}

# add gender as a color three different ways:
# - points only
# - labels only
# - both

ggplot(got, aes(x=moral,y=physical)) + 
  geom_point(aes(color=gender)) + 
  geom_text(aes(label=label), nudge_y = -.025)

ggplot(got, aes(x=moral,y=physical)) + 
  geom_point(aes()) + 
  geom_text(aes(label=label, color=gender), nudge_y = -.025)

ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  geom_point(aes()) + 
  geom_text(aes(label=label), nudge_y = -.025)


```

## Turn off legend for text layer

```{r}

# hint: there is another property for the geom_text layer that might help

ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  geom_point(aes()) + 
  geom_text(aes(label=label), nudge_y = -.025, show.legend = FALSE)

```


## Switch direction of Y axis

```{r}

# hint: edits to axes often use scales
# check https://ggplot2.tidyverse.org/reference/#section-scales for pre-built scales 
# that might help (focus on scales for the y-axis)

ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  geom_point(aes()) + 
  geom_text(aes(label=label), nudge_y = -.025, show.legend = FALSE) + 
  scale_y_reverse()

```

## Add reference lines

```{r}

# hint: there are special geoms for straight lines;
# check https://ggplot2.tidyverse.org/reference/#section-layer-geoms for all geom options

ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  geom_point(aes()) + 
  geom_text(aes(label=label), nudge_y = -.025, show.legend = FALSE) + 
  scale_y_reverse() +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5)

```

```{r}

# look at how ggplot2 is layering the plot; rearrange layers as needed

ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  scale_y_reverse() +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5)+ 
  geom_point(aes())  + 
  geom_text(aes(label=label), nudge_y = -.025, show.legend = FALSE)

```

## Change the theme

```{r}

# Try to find a theme closer to the NYT chart;
# see https://ggplot2.tidyverse.org/reference/#section-themes for built-in themes

ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  scale_y_reverse() +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5)+ 
  geom_point(aes())  + 
  geom_text(aes(label=label), nudge_y = -.025, show.legend = FALSE) +
  theme_bw()

```

## Change axis limits

```{r}

# the chart might look better if the axes go all the way from 0 to 1; edit
# the axes to force them to include 0 and 1
# hint: remember that changes to axes usually involve a scale

ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  scale_y_reverse(lim=c(1,0)) +
  scale_x_continuous(limits=c(0,1)) +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5)+ 
  geom_point(aes())  + 
  geom_text(aes(label=label), nudge_y = -.025, show.legend = FALSE) +
  theme_bw()


```

## Annotate the axes with descriptive text

```{r}

# hint: geoms are typically best for chart elements involving data;
# look for another feature that can add text to charts
# https://ggplot2.tidyverse.org/reference/

ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  scale_y_reverse(lim=c(1,0)) +
  scale_x_continuous(limits=c(0,1)) +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5)+ 
  geom_point(aes())  + 
  geom_text(aes(label=label), nudge_y = -.025, show.legend = FALSE) +
  theme_bw() +
  annotate(geom = "text", x=.5, y=1, label="Ugly") +
  annotate(geom = "text", x=.5, y=0, label="Beautiful") +
  annotate(geom = "text", x=0, y=.48, label="Evil") +
  annotate(geom = "text", x=1, y=.52, label="Good") 

# alternate syntax - combine all annotations into one layer

ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  scale_y_reverse(lim=c(1,0)) +
  scale_x_continuous(limits=c(0,1)) +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5)+ 
  geom_point(aes())  + 
  geom_text(aes(label=label), nudge_y = -.025, show.legend = FALSE) +
  theme_bw() +
  annotate(geom = "text", x=c(.5,.5,0,1), y=c(1,0,.48,.52), label=c("Ugly","Beautiful","Evil","Good"))

```

