---
title: "Game of Thromes Character Ratings"
author: "Angela Zoss"
date: "3/5/2023"
output: html_document
---

## Setup your environment

```{r}

# Load required libraries

library(tidyverse)
library(here)
here::i_am("Day 1/3-got_nyt_final.Rmd")

```

## Load your data

```{r}

# data comes from https://int.nyt.com/newsgraphics/2017/2017-07-17-got-matrix/mean.json
# data based on ratings using tool at https://www.nytimes.com/interactive/2017/08/09/upshot/game-of-thrones-chart.html

got <- read_csv(here("data", "got_ratings.csv"))

```

## Create a scatterplot of `moral` vs. `physical`

```{r}



```

## Set the alpha aesthetic (which controls transparency) for all points to .75

```{r}

# check ?geom_point to see names of the different options available
# where should the new option go? what layer? inside or outside of aesthetics?



```

## Add a new geom that will display labels for each point

```{r}

# hint: check https://ggplot2.tidyverse.org/reference/#section-geoms for all geom options



```

## Adjust label position to limit overlap with points

```{r}

# hint: look at ?geom_text for an option that might change the position slightly
# where should the new option go? what layer? inside or outside of aesthetics?



```

## Inheritance: Add colors

```{r}

# add gender as a color three different ways:
# - points only
# - labels only
# - both



```

## Turn off legend for text layer

```{r}

# hint: there is another property for the geom_text layer that might help



```

