---
title: "Mapping in R"
author: "Angela Zoss"
date: "8/13/2018"
output: github_document
---

## Setup your environment

```{r}

# Load required libraries

library(tidyverse)

#install.packages("maps")
library(maps)

#install.packages("mapproj")
library(mapproj)

```

## California counties, random data

```{r}

# load in the data for each county in California; 
# this function comes from the "maps" package, which gets loaded automatically

county_map <- map_data("county","california")

county_map <- county_map %>% group_by(subregion) %>% mutate(rand = runif(1))

# ?map_data for more information about how to get basic polygons

ggplot(county_map) + 
  geom_polygon(aes(x = long,
                   y = lat,
                   group=group,
                   fill=rand)) +
  coord_map()

```

## Buildings in Calaveras County, CA

```{r}

# load in building data from a csv file
point_locations <- read_csv("data/Calaveras-County-Government-Offices.csv")

# color definitions; change these to change the look of the map
default_county_color <- "white"
default_county_border <- "gray80"
cal_county_color <- "white"
cal_county_border <- "red"
dot_color <- "blue"
dot_size <- 2 #can change this if the dots are too small or large
dot_transparency <- 0.5 #can change this if the dots are too light or dark

# three different ggplot pieces; one for all the counties, one for calaveras, and one for the lat/lon points
map_counties <- geom_polygon(data = county_map, aes(x = long, y = lat, group=group), fill=default_county_color, color=default_county_border)

map_calaveras <- geom_polygon(data = county_map[county_map$subregion=="calaveras",], aes(x = long, y = lat, group=group), fill=cal_county_color, color = cal_county_border, size=1)

map_points <- geom_point(data=point_locations, aes(x=Longitude, y=Latitude), color=dot_color, size=dot_size, alpha=dot_transparency)

# add everything into a single map object, then display the map
mp <- ggplot()
mp <- mp + map_counties 
mp

mp <- mp + map_calaveras
mp

mp <- mp + map_points
mp

# so far, the map is just displaying as if it's normal x/y data; we can add a
# coordinate system to project the map into a more normal ratio
# default projection is mercator(); other options are listed at ?mapproject

mp <- mp + coord_map()
mp

# optional: can zoom into map, using these long/lat as the new boundaries
zoom_long_left <- -122.0
zoom_long_right <- -119.0
zoom_lat_top <- 39.5
zoom_lat_bottom <- 37.0

# add this line (below) to zoom in 
# (that is, change the minimum and maximum values shown)
mp <- mp + coord_map(xlim=c(zoom_long_left,zoom_long_right),
                     ylim=c(zoom_lat_bottom,zoom_lat_top))
mp

```

## El Niño measurements

```{r}

elnino <- read_csv("data/elnino.csv", na=c(".",NA), 
                   col_types = cols(Date = col_date(format="%y%m%d"))) %>% 
  type_convert()

elnino$Longitude <- ifelse(elnino$Longitude < 0, 360+elnino$Longitude,elnino$Longitude)

# load in the data for each county in California; 
# this function comes from the "maps" package, which gets loaded automatically

world_map <- map_data("world2")

# ?map_data for more information about how to get basic polygons

# color definitions; change these to change the look of the map
default_county_color <- "white"
default_county_border <- "gray80"

dot_color <- "blue"
dot_size <- 2 #can change this if the dots are too small or large
dot_transparency <- 0.5 #can change this if the dots are too light or dark

# three different ggplot pieces; one for all the counties, one for calaveras, and one for the lat/lon points
map_countries <- geom_polygon(data = world_map, aes(x = long, y = lat, group=group), fill=default_county_color, color=default_county_border)

map_buoys <- geom_point(aes(x=elnino$Longitude, y=elnino$Latitude), color=dot_color, size=dot_size, alpha=dot_transparency)

map_bin2d <- geom_bin2d(aes(x=elnino$Longitude, y=elnino$Latitude))

# add everything into a single map object, then display the map
mp <- ggplot()
mp <- mp + map_countries 
mp

mp + map_buoys
mp + map_bin2d


```

