---
title: "2020 Inclusiveness Index"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)

# data load script is written for exercise file folder, not templates folder
source('../data/inclusiveness_index/load_inclusiveness_index.R')

```

Row {data-height=150}
-----------------------------------------------------------------------

### About The Data

Stephen Menendian, Elsadig Elsheikh and Samir Gambhir, 2020 Inclusiveness Index: Measuring Global Inclusion and Marginality (Berkeley, CA: Othering & Belonging Institute, 2021), https://belonging.berkeley.edu/inclusivenessindex.

Row
-----------------------------------------------------------------------

### {data-width=500}
    
```{r}

ggplot(data = inclusiveness_index,
       mapping = aes(x = Continent,
                     fill = Index.categories.2020)) +
  geom_bar()

```

### {data-width=500}
```{r}

ggplot(data = inclusiveness_index, 
       mapping = aes(x = Inclusiveness.index.2020,
                     fill = Index.categories.2020)) +
  geom_histogram()

```

Row
-----------------------------------------------------------------------

### {}
    
```{r}

ggplot(data = inclusiveness_index,
       mapping = aes(x = Z.score.Religion,
                     y = Inclusiveness.index.2020,
                     color=Continent)) +
  geom_point() 

```
   