---
title: "Interactive charts with plotly"
author: "Angela Zoss"
date: "9/14/2019"
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```


## Setup your environment

```{r}

# Load required libraries

library(tidyverse)
library(plotly)

#install.packages("maps")
library(maps)

#install.packages("mapproj")
library(mapproj)

#install.packages("sf")
library(sf)


```

## Game of Thrones Data Exploration

```{r}

# data comes from https://int.nyt.com/newsgraphics/2017/2017-07-17-got-matrix/mean.json
# data based on ratings using tool at https://www.nytimes.com/interactive/2017/08/09/upshot/game-of-thrones-chart.html

got <- read_csv("data/got_ratings.csv")

got_expl <- ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  geom_point(alpha=.75) + 
  geom_text(aes(label=label), nudge_y = -.015, show.legend = FALSE)

got_expl

```


```{r}

# use ggplotly() function to convert ggplot2 chart to interactive plotly chart



```

```{r}

# building the chart natively in plotly
# what differences do you notice?

plot_ly(data = got, x = ~moral, y = ~physical, color = ~gender) %>%
  add_markers() %>%
  add_text(textposition = "top center", text = ~label, showlegend = FALSE)

```

## Star Wars Character Data

```{r}

# built-in data

starwars_chars <- starwars

sw_height <- ggplot(starwars_chars) +
  geom_histogram(aes(height))

sw_height

```

```{r}

# use ggplotly() function to convert ggplot2 chart to interactive plotly chart



```

```{r}

# finish the plot_ly call to recreate the chart natively
# (add variable assignments for data and x)
  
plot_ly(data = ..., x = ~..., type = "histogram")

```


```{r}

# original chart

sw_char <- ggplot(starwars_chars, aes(height,mass)) +
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) + 
  geom_text(data=starwars_chars %>% dplyr::filter(mass == max(mass, na.rm=T) | height == min(height, na.rm=T)), aes(label=name), nudge_y = 50)

sw_char

```

```{r}

# use ggplotly() function to convert ggplot2 chart to interactive plotly chart



```

```{r}

# try making this one yourself
# hint: you can specify a new dataset for different layers, just like in ggplot2
# also hint: you'll be adding three layers - markers, lines, text
# which is easier - plotly or ggplot2?



```

## Star Wars Opinion Data

```{r}

# original chart

# data from https://fivethirtyeight.com/features/americas-favorite-star-wars-movies-and-least-favorite-characters/
# note: CSV has two rows of headers, so I have manually created a list of headers and am adding
# that after loading just the data rows

new_names <- read_csv('data/StarWarsNames.csv') %>% select(NewNames)
  
starwars_opins <- read_csv('data/StarWars.csv', skip=2, col_names=FALSE) %>% setNames(unlist(new_names))

starwars_opins_tidy <- starwars_opins %>% dplyr::select(RespondentID, starts_with("Opinion")) %>% gather("Character","Opinion",-RespondentID) %>% mutate(Character=sub("Opinion","",Character)) %>% na.omit()

combined <- starwars_opins_tidy %>% dplyr::filter(Character %in% c("Solo", "JarJar"))

opinion.levels <- c("Unfamiliar (N/A)","Very unfavorably","Somewhat unfavorably",
                    "Neither favorably nor unfavorably (neutral)",
                    "Somewhat favorably","Very favorably")

combined.f <- combined %>% 
         mutate(Opinion=factor(Opinion, opinion.levels))

opinion.colors <- c("grey50","firebrick4","firebrick1","grey85","dodgerblue1","dodgerblue4")

sw_opin <- ggplot(combined.f) +
  geom_bar(aes(Opinion, fill=Opinion), show.legend = FALSE) +
  facet_wrap(vars(Character)) +
  coord_flip() +
  scale_fill_manual(values = opinion.colors) +
  theme_minimal()

sw_opin


```

```{r}

# use ggplotly() function to convert ggplot2 chart to interactive plotly chart
# what happens?


```

```{r}

# reproducing the faceted bar chart in plotly with subplots

han <- plot_ly(combined.f %>% dplyr::filter(Character == "Solo") %>% drop_na(Opinion) %>% count(Opinion)) %>%
  add_bars(x = ~n, y = ~Opinion, orientation = 'h', color = ~Opinion, showlegend = FALSE) %>%
  layout( xaxis = list(range = c(0, 620)),
          annotations = list(
  text = "Han Solo",
  xref = "paper",
  yref = "paper",
  yanchor = "bottom",
  xanchor = "center",
  align = "center",
  x = 0.5,
  y = 1,
  showarrow = FALSE
))

jarjar <- plot_ly(combined.f %>% dplyr::filter(Character == "JarJar") %>% drop_na(Opinion) %>% count(Opinion)) %>%
  add_bars(x = ~n, y = ~Opinion, orientation = 'h', color = ~Opinion, showlegend = FALSE) %>%
  layout( xaxis = list(range = c(0, 620)),
          annotations = list(
  text = "Jar Jar Binks",
  xref = "paper",
  yref = "paper",
  yanchor = "bottom",
  xanchor = "center",
  align = "center",
  x = 0.5,
  y = 1,
  showarrow = FALSE
))

subplot(han, jarjar, shareY = T)

```

## Gapminder Average

```{r}

# original chart

gap <- read_csv("data/gapminder_avg.csv")
names(gap) <- make.names(names(gap), unique=TRUE)

gap_plot <- ggplot(gap, aes(x=Average.GDP.per.capita, y=Average.Life.expectancy.at.birth)) +
  geom_point(aes(size=Average.Total.population, color=Region)) +
  scale_x_log10() + 
  labs(x="Average GDP per capita (log 10)", y="Average life expectancy at birth", title="Averages across all years of the traditional Gapminder dataset") +
  scale_size_continuous(name="Average total population", breaks=c(7500000,75000000,750000000),labels=c("7.5 million","75 million","750 million")) +
  geom_smooth(method="lm", se=FALSE, color="gray50") +
  geom_text(data=gap %>% filter(Average.Total.population>200000000), aes(label=Country)) +
  theme_bw()

gap_plot

```

```{r}

# use ggplotly() function to convert ggplot2 chart to interactive plotly chart


```

```{r}

# reproduce the chart in plotly


```

## Mapping with sf

```{r}

nc <- system.file("gpkg/nc.gpkg", package="sf") %>% read_sf() %>% st_transform(32119)

nc_map <- ggplot(nc) +
  geom_sf(aes(fill=BIR74)) +
    scale_fill_gradientn(colors = sf.colors())

nc_map

```


```{r}

# use ggplotly() function to convert ggplot2 chart to interactive plotly chart



```


```{r}

# plotly needs a slightly different data load process
nc2 <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)

plot_ly(nc2, split=~NAME, color = ~BIR74, showlegend=F)

```