---
title: "Interactive charts with plotly"
author: "Angela Zoss"
date: "8/14/2018"
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```


## Setup your environment

```{r}

# Load required libraries

library(tidyverse)
library(plotly)

```

## Game of Thrones Data Exploration

```{r}

# data comes from https://int.nyt.com/newsgraphics/2017/2017-07-17-got-matrix/mean.json
# data based on ratings using tool at https://www.nytimes.com/interactive/2017/08/09/upshot/game-of-thrones-chart.html

got <- read_csv("data/got_ratings.csv")

got_expl <- ggplot(got, aes(x=moral,y=physical)) + 
  geom_point(size=5, color="firebrick", alpha=.75) +
  labs(title="The moral and physical ratings of characters from Game of Thrones") +
  geom_smooth(method="lm", se=FALSE)

got_expl

```


```{r}

ggplotly(got_expl)

```

```{r}

plot_ly(data = got, x = ~moral) %>%
  add_markers(y = ~physical,
        marker = list(size = 15,
                       color = 'rgba(178, 34, 34, .75)'),
        showlegend = FALSE) %>%
  add_lines(y = ~fitted(lm(physical~moral)), showlegend = FALSE,
                           line = list(color = '#0000ff')) %>%
  layout(title = "The moral and physical ratings of characters from Game of Thrones")



```



## Game of Thrones New York Times

```{r}

got_nyt <- ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  scale_y_reverse(lim=c(1,0)) +
  scale_x_continuous(limits=c(0,1)) +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5)+ 
  geom_point(aes())  + 
  geom_text(aes(label=label), nudge_y = -.025, show.legend = FALSE) +
  theme_bw() +
  annotate(geom = "text", x=c(.5,.5,0,1), y=c(1,0,.48,.52), label=c("Ugly","Beautiful","Evil","Good"))

got_nyt

```

```{r}

ggplotly(got_nyt)

```

```{r}

plot_ly(data = got) %>%
  add_markers(x = ~moral, y = ~physical, color = ~gender, colors=c("red","blue")) %>%
  add_text(x = ~moral, y = ~physical, color = ~gender, colors=c("red","blue"), text = ~label, showlegend=FALSE, textposition="bottom center") %>%
  add_segments(x = .5, xend = .5, y = 0, yend = 1, line = list(color = "black"), showlegend = FALSE) %>%
  add_segments(x = 0, xend = 1, y = .5, yend = .5, line = list(color = "black"), showlegend = FALSE) %>%
  add_annotations(x= 0.5,y= 0,text = "Beautiful",showarrow = F) %>%
  add_annotations(x= 0.5,y= 1,text = "Ugly",showarrow = F) %>%
  add_annotations(x= 0,y= 0.5,text = "Evil",showarrow = F) %>%
  add_annotations(x= 1,y= 0.5,text = "Good",showarrow = F) %>%
  layout(yaxis = list(autorange = "reversed",zeroline = F),
         xaxis = list(zeroline = F))



```


## Star Wars Character Data

```{r}

# built-in data

starwars_chars <- starwars

sw_char <- ggplot(starwars_chars, aes(height,mass)) +
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) + 
  geom_text(data=starwars_chars %>% filter(mass > 1000), aes(label=name), nudge_y = -50) + 
  geom_text(data=starwars_chars %>% filter(height < 75), aes(label=name), nudge_y = 50)

sw_char
```

```{r}

ggplotly(sw_char)

```

```{r}

# make this one yourself
# hint: you can specify a new dataset for different layers, just like in ggplot2

plot_ly(data = starwars_chars %>% dplyr::select(name, mass, height) %>% na.omit(), 
        x = ~height) %>%
  add_markers(y = ~mass, showlegend = FALSE) %>%
  add_lines(y = ~fitted(lm(mass~height)), showlegend = FALSE) %>%
  add_text(data = starwars_chars %>% filter(!is.na(mass)) %>% filter(mass == max(mass) | height == min(height)), x = ~height, y = ~mass, text = ~name, textposition="top center")


```

```{r}
sw_char2 <- ggplot(starwars_chars %>% filter(!is.na(birth_year)), aes(birth_year, fct_reorder(as_factor(name),birth_year))) +
  geom_point() +
  labs(y="name", x="age")

sw_char2

```

```{r}

ggplotly(sw_char2)

```

```{r}

plot_ly(starwars_chars %>% filter(!is.na(birth_year))) %>%
  add_markers(x = ~birth_year, y = ~fct_reorder(as_factor(name),birth_year)) %>%
  layout(yaxis = list(title="name"),
         xaxis = list(title="age"))

```

## Star Wars Opinion Data

```{r}

# data from https://fivethirtyeight.com/features/americas-favorite-star-wars-movies-and-least-favorite-characters/
# note: CSV has two rows of headers, so I have manually created a list of headers and am adding
# that after loading just the data rows

new_names <- read_csv('data/StarWarsNames.csv') %>% select(NewNames)
  
starwars_opins <- read_csv('data/StarWars.csv', skip=2, col_names=FALSE) %>% setNames(unlist(new_names))

sw_opin <- ggplot(starwars_opins) +
  geom_bar(aes(1,fill=SeenAnyYN),show.legend = FALSE) +
  coord_polar(theta="y") +
  geom_text(data=starwars_opins %>% count(SeenAnyYN) %>% mutate(total=sum(n),label=paste0(SeenAnyYN,"\n",round(n/total*100,1),"%")),aes(c(1,1),c(1050,450),label=label)) +
  theme_void() +
  labs(title="Have you seen any of the 6 films in the Star Wars franchise?")

sw_opin

opinion.levels <- c("Unfamiliar (N/A)","Very unfavorably","Somewhat unfavorably",
                    "Neither favorably nor unfavorably (neutral)",
                    "Somewhat favorably","Very favorably")


```

```{r}

ggplotly(sw_opin)

```

```{r}

plot_ly(starwars_opins %>% count(SeenAnyYN)) %>%
  add_pie(labels = ~SeenAnyYN, values = ~n, textinfo="label+percent", showlegend=F) %>%
  layout(title="Have you seen any of the 6 films in the Star Wars franchise?")

```

```{r}

sw_opin2 <- ggplot(starwars_opins %>% select(OpinionSolo,OpinionJarJar) %>% gather(character,opinion) %>% na.omit() %>% mutate(opinion=factor(opinion, opinion.levels))) +
  geom_bar(aes(opinion,fill=opinion),show.legend = FALSE) +
  facet_grid(.~character) +
  coord_flip() +
  scale_fill_manual(values = c("grey50","firebrick4","firebrick1","grey85","dodgerblue1","dodgerblue4")) +
  theme_minimal()

sw_opin2

```

```{r}

ggplotly(sw_opin2)

```

```{r}

han <- plot_ly(starwars_opins %>% na.omit(OpinionSolo) %>% count(OpinionSolo) %>% mutate(OpinionSolo=factor(OpinionSolo, opinion.levels))) %>%
  add_bars(x = ~n, y = ~OpinionSolo, orientation = 'h', color = ~OpinionSolo, showlegend = FALSE) %>%
  layout( xaxis = list(range = c(0, 115)),
          annotations = list(
  text = "Han Solo",
  xref = "paper",
  yref = "paper",
  yanchor = "bottom",
  xanchor = "center",
  align = "center",
  x = 0.5,
  y = 1,
  showarrow = FALSE
))

jarjar <- plot_ly(starwars_opins %>% na.omit(OpinionJarJar) %>% count(OpinionJarJar) %>% mutate(OpinionJarJar=factor(OpinionJarJar, opinion.levels))) %>%
  add_bars(x = ~n, y = ~OpinionJarJar, orientation = 'h', color = ~OpinionJarJar, showlegend = FALSE) %>%
  layout(xaxis = list(range = c(0, 115)),
          annotations = list(
  text = "Jar Jar Binks",
  xref = "paper",
  yref = "paper",
  yanchor = "bottom",
  xanchor = "center",
  align = "center",
  x = 0.5,
  y = 1,
  showarrow = FALSE
))

subplot(han, jarjar, shareY = T)

```

## Gapminder Average

```{r}

# data comes from http://www.gapminder.org/

gap <- read_csv("data/gapminder_avg.csv")
names(gap) <- make.names(names(gap), unique=TRUE)

gap_plot <- ggplot(gap, aes(x=Average.GDP.per.capita, y=Average.Life.expectancy.at.birth)) +
  geom_point(aes(size=Average.Total.population, color=Region)) +
  scale_x_log10() + 
  labs(x="Average GDP per capita (log 10)", y="Average life expectancy at birth", title="Averages across all years of the traditional Gapminder dataset") +
  scale_size_continuous(name="Average total population", breaks=c(7500000,75000000,750000000),labels=c("7.5 million","75 million","750 million")) +
  geom_smooth(method="lm", se=FALSE, color="gray50") +
  geom_text(data=gap %>% filter(Average.Total.population>200000000), aes(label=Country)) +
  theme_bw()

gap_plot

```

```{r}

ggplotly(gap_plot)

```

```{r}

plot_ly(gap, x = ~Average.GDP.per.capita) %>%
  add_markers(y = ~Average.Life.expectancy.at.birth, size = ~Average.Total.population, color = ~Region) %>%
  add_lines(y = ~fitted(lm(Average.Life.expectancy.at.birth~log(Average.GDP.per.capita))),showlegend = F, line = list(color = '#555555')) %>%
  layout(xaxis = list(type = "log")) %>%
  add_text(data = gap %>% filter(Average.Total.population > 200000000), y = ~Average.Life.expectancy.at.birth, text = ~Country, textposition="top center", showlegend=F)


```