---
title: "R Visualization Portfolio"
author: "Angela Zoss"
date: "8/14/2018"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(plotly)
```

```{r}

# Loading data before anything renders

starwars_chars <- starwars

new_names <- read_csv('data/StarWarsNames.csv') %>% select(NewNames)
  
starwars_opins <- read_csv('data/StarWars.csv', skip=2, col_names=FALSE) %>% setNames(unlist(new_names))

starwars_opins_tidy <- starwars_opins %>% dplyr::select(RespondentID, starts_with("Opinion")) %>% gather("Character","Opinion",-RespondentID) %>% mutate(Character=sub("Opinion","",Character)) %>% na.omit()

combined <- starwars_opins_tidy %>% dplyr::filter(Character %in% c("Solo", "JarJar"))

opinion.levels <- c("Unfamiliar (N/A)","Very unfavorably","Somewhat unfavorably",
                    "Neither favorably nor unfavorably (neutral)",
                    "Somewhat favorably","Very favorably")

combined.f <- combined %>% 
         mutate(Opinion=factor(Opinion, opinion.levels))

got <- read_csv("data/got_ratings.csv")

gap <- read_csv("data/gapminder_avg.csv")
names(gap) <- make.names(names(gap), unique=TRUE)

```

```{r}

# flexdashboard layouts:
# https://rmarkdown.rstudio.com/flexdashboard/layouts.html

```


Game of Thrones
=====================================  

Column {.tabset}
-------------------------------------

### ggplotly

```{r}

got_expl <- ggplot(got, aes(x=moral,y=physical, color=gender)) + 
  geom_point(alpha=.75) + 
  geom_text(aes(label=label), nudge_y = -.015, show.legend = FALSE)

ggplotly(got_expl)


```

### plot_ly

```{r}

plot_ly(data = got, x = ~moral, y = ~physical, color = ~gender) %>%
  add_markers() %>%
  add_text(textposition = "top center", text = ~label, showlegend = FALSE)

```

Star Wars
=====================================  

Column {data-width=650}
-----------------------------------------------------------------------

### Star Wars characters by mass and height

```{r}

plot_ly(data = starwars_chars %>% dplyr::select(name, mass, height) %>% na.omit(), 
        x = ~height) %>%
  add_markers(y = ~mass, showlegend = FALSE) %>%
  add_lines(y = ~fitted(lm(mass~height)), showlegend = FALSE) %>%
  add_text(data = starwars_chars %>% dplyr::filter(mass == max(mass, na.rm=T) | height == min(height, na.rm=T)), x = ~height, y = ~mass, text = ~name, textposition="top center")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Height distribution of Star Wars characters

```{r}

plot_ly(data = starwars_chars, x = ~height, type = "histogram")

```

### How do opinions of Han Solo compare to opinions of Jar Jar Binks?

```{r}

han <- plot_ly(combined.f %>% dplyr::filter(Character == "Solo") %>% drop_na(Opinion) %>% count(Opinion)) %>%
  add_bars(x = ~n, y = ~Opinion, orientation = 'h', color = ~Opinion, showlegend = FALSE) %>%
  layout( xaxis = list(range = c(0, 620)),
          annotations = list(
  text = "Han Solo",
  xref = "paper",
  yref = "paper",
  yanchor = "bottom",
  xanchor = "center",
  align = "center",
  x = 0.5,
  y = 1,
  showarrow = FALSE
))

jarjar <- plot_ly(combined.f %>% dplyr::filter(Character == "JarJar") %>% drop_na(Opinion) %>% count(Opinion)) %>%
  add_bars(x = ~n, y = ~Opinion, orientation = 'h', color = ~Opinion, showlegend = FALSE) %>%
  layout( xaxis = list(range = c(0, 620)),
          annotations = list(
  text = "Jar Jar Binks",
  xref = "paper",
  yref = "paper",
  yanchor = "bottom",
  xanchor = "center",
  align = "center",
  x = 0.5,
  y = 1,
  showarrow = FALSE
))

subplot(han, jarjar, shareY = T)

```

Gapminder
=====================================  

```{r}

plot_ly(gap, x = ~Average.GDP.per.capita) %>%
  add_markers(y = ~Average.Life.expectancy.at.birth, size = ~Average.Total.population, color = ~Region) %>%
  add_lines(y = ~fitted(lm(Average.Life.expectancy.at.birth~log(Average.GDP.per.capita))),showlegend = F, line = list(color = '#555555')) %>%
  layout(xaxis = list(type = "log")) %>%
  add_text(data = gap %>% filter(Average.Total.population > 200000000), y = ~Average.Life.expectancy.at.birth, text = ~Country, textposition="top center", showlegend=F)


```

