---
title: "R Visualization Portfolio with Shiny"
author: "Angela Zoss"
date: "8/14/2018"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}

library(tidyverse)
library(flexdashboard)

starwars_chars <- starwars %>% na.omit() %>% mutate(name=fct_reorder(as_factor(name),birth_year))

got <- read_csv("data/got_ratings.csv")

```

```{r}

# modeled after https://jjallaire.shinyapps.io/shiny-ggplot2-brushing/

selectedData <- reactive({
  brushedPoints(starwars_chars, input$plot1_brush)
})
```

```{r}

# flexdashboard layouts:
# https://rmarkdown.rstudio.com/flexdashboard/layouts.html

```


Game of Thrones
=====================================  

Column {.sidebar}
-------------------------------------

```{r}

selectInput("gotcolor", "Select Variable for Color:", c("gender","loyalty"))

sliderInput("labelsize", "Change Label Font Size:", 1,10,4, step=1)

```

Column 
-------------------------------------

```{r}

renderPlot({ggplot(got, aes_string(x="moral",y="physical", color=input$gotcolor)) + 
  scale_y_reverse(lim=c(1,0)) +
  scale_x_continuous(limits=c(0,1)) +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5)+ 
  geom_point(aes())  + 
  geom_text(aes(label=label), nudge_y = -.025, show.legend = FALSE, size=as.numeric(input$labelsize)) +
  theme_bw() +
  annotate(geom = "text", x=c(.5,.5,0,1), y=c(1,0,.48,.52), label=c("Ugly","Beautiful","Evil","Good"))}, width=8*96, height=7*96, res=96)

```

Star Wars {data-orientation=rows}
=====================================  

Row {data-height=25}
-----------------------------------------------------------------------

*Instructions: Drag a box on the left plot to highlight points on the right plot.*

Row
-----------------------------------------------------------------------

### Star Wars characters by birth year


```{r}
plotOutput("plot1", brush = brushOpts(id = "plot1_brush"))
output$plot1 <- renderPlot({
  ggplot(starwars_chars, aes(birth_year, name)) +
  geom_point(size=5)
})
```


### Star Wars characters by mass and height

```{r}

renderPlot({
  ggplot(starwars_chars, aes(height,mass)) +
  geom_point(size=5) + 
    geom_point(data=selectedData(), aes(height,mass), color="red", size=5) +
    scale_x_continuous(limits=c(min(starwars_chars$height),(max(starwars_chars$height)))) +
    scale_y_continuous(limits=c(min(starwars_chars$mass),(max(starwars_chars$mass))))
  })

```


