---
title: "R Visualization Portfolio with Shiny"
author: "Angela Zoss"
date: "8/14/2018"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}

library(tidyverse)
library(flexdashboard)

starwars_chars <- starwars %>% na.omit() %>% mutate(name=fct_reorder(as_factor(name),birth_year))

got <- read_csv("data/got_ratings.csv")

```

```{r}

# modeled after https://jjallaire.shinyapps.io/shiny-ggplot2-brushing/

# This is a reactive function, like renderPlot -- notice the use of {}
# That means it will react to user input
# In this case, we are creating a pair of charts where selecting points on one
# highlights points on the other
# This reactive function helps determing which points were selected by using a "brush"

selectedData <- reactive({
  brushedPoints(starwars_chars, input$plot1_brush)
})
```

```{r}

# flexdashboard layouts:
# https://rmarkdown.rstudio.com/flexdashboard/layouts.html

```


Game of Thrones
=====================================  

Column {.sidebar}
-------------------------------------

```{r}

# add the input controls to the sidebar

```

Column 
-------------------------------------

```{r}

# add the renderPlot to the main panel

```

Star Wars {data-orientation=rows}
=====================================  

Row {data-height=25}
-----------------------------------------------------------------------

*Instructions: Drag a box on the left plot to highlight points on the right plot.*

Row
-----------------------------------------------------------------------

### Star Wars characters by birth year


```{r}

# to add the brush input to the plot, we have to add an explicit call 
# to "plotOutput", instead of just using renderPlot

# to connect the plotOutput to the renderPlot code, we specify an outputId for
# the plotOutput, and then we save renderPlot to the output$ object using that ID

plotOutput("plot1", brush = brushOpts(id = "plot1_brush"))

output$plot1 <- renderPlot({
  
  # add the Star Wars character birth year plot, ggplot2 version
  
})
```


### Star Wars characters by mass and height

```{r}

renderPlot({
  ggplot(starwars_chars, aes(height,mass)) +
    geom_point(size=5) + 
    # add another geom_point that uses selectedData() for the data and colors the points red
    scale_x_continuous(limits=c(min(starwars_chars$height),(max(starwars_chars$height)))) +
    scale_y_continuous(limits=c(min(starwars_chars$mass),(max(starwars_chars$mass))))
  })

```


