---
title: "Shiny controls in flexdashboard"
author: "Angela Zoss"
date: "8/9/2021"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}

library(tidyverse)
library(flexdashboard)
library(DT)
library(plotly)
library(crosstalk)

source('data/inclusiveness_index/load_inclusiveness_index.R')

# Wrap data frame in SharedData
shared_incl <- SharedData$new(inclusiveness_index, ~Country.Code)

got <- read_csv("data/got_ratings.csv")

```

```{r}

# flexdashboard layouts:
# https://rmarkdown.rstudio.com/flexdashboard/layouts.html

```


Inclusiveness Index {data-orientation=rows}
=====================================  

Inputs {.sidebar}
-----------------------------------------------------------------------

### Set Your Filters

```{r}

filter_checkbox(id="sel_continent",
              label="Select Continent:",
              sharedData=shared_incl,
              group=~Continent,
              inline = TRUE)

filter_select(id="sel_subregion",
              label="Select Sub-region:",
              sharedData=shared_incl,
              group=~Sub.Region)

```

### About flexdashboard

Flexdashboard is a library that takes R Markdown documents and turns them into a website. You can build up different website layout elements like pages, panels, rows, and columns. In each part of your website, you can use a blend of text/image content and R code, just like in normal R Markdown documents. A flexdashboard document can be compiled (or "knit") to an HTML file that can then be shared as a file or published as a website.

Row
-----------------------------------------------------------------------

### {data-width=500}
    
```{r}

plot_ly(shared_incl, x = ~Inclusiveness.index.2020, type = 'histogram')

```

### {data-width=500}
```{r}

plot_ly(shared_incl, x = ~Z.score.Religion, y = ~Inclusiveness.index.2020, color = ~Continent)

```

Row
-----------------------------------------------------------------------

### {}
    
```{r}

DT::datatable(shared_incl, 
                options = list(
              pageLength = 5,
              lengthMenu = c(5, 10, 15, 20)
            ))

```
   
Game of Thrones
=====================================  

Column {.sidebar}
-------------------------------------

```{r}

# This page of the dashboard will show the Game of Thrones customized plot,
# but it will use Shiny inputs to make it responsive to user input. One input
# will change the variable that is used for color in the plot. The other input
# will change the size of the data labels.

# Add the two Shiny input widgets here: one select box to change the variable 
# for the color aesthetic and one slider to change the label size.

# for the select box:
#  - use the inputId "gotcolor"
#  - write a descriptive label
#  - include the following choices: gender and loyalty

# for the slider:
#  - use the inputId "labelsize"
#  - write a descriptive label
#  - play around with values for min, max, value, and step

selectInput(inputId = "gotcolor", 
            label = "Select Variable for Color:", 
            choices = c("gender","loyalty"))

sliderInput(inputId = "labelsize", 
            label = "Change Label Font Size:", 
            min = 1,
            max = 10,
            value = 4, 
            step = 1)

```

Column 
-------------------------------------

```{r}

# If you set up the inputs correctly, this plot should respond to changes to
# the inputs. If you have trouble getting things to work, look for the "input$"
# placeholders in the code below and switch them out for default values like "gender"
# and 4.

# Once you have the inputs connected to the output correctly, review the code
# below to see if it makes sense, focusing on the places where you see "input$."
# What is different about this plot, compared to previous versions of the plot?
# What can you infer about the Shiny inputs and the kinds of data they return?

renderPlot({ggplot(got, aes_string(x="moral",y="physical", color=input$gotcolor)) + 
  scale_y_reverse(lim=c(1,0)) +
  scale_x_continuous(limits=c(0,1)) +
  geom_hline(yintercept=.5, color = "gray70") +
  geom_vline(xintercept=.5, color = "gray70")+ 
  geom_point(aes())  + 
  geom_text(aes(label=label), nudge_y = -.025, show.legend = FALSE, 
            size=as.numeric(input$labelsize)) +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank()) +
  annotate(geom = "text", x=c(.5,.5,0,1), y=c(1,0,.48,.52), 
           label=c("Ugly","Beautiful","Evil","Good"))}, width=8*96, height=7*96, res=96)

```


